blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/edridudi/koios-typescript-client/discussions
    about: Please discuss non bug-related topics there
